### ISSUE TITLE
Please host this on Gitlab

### ISSUE THREAD

**Issue by 60secs** [luongvo209/Short-Gitlab-Tutorial#3]
Avoids the obvious dogfooding elephant

**Comment by zaquestion** [comment]
Push mirror is free with GitLab now so its pretty harmless to mirror this over. That said, it seems like a GitLab tutorial targeted at GitHub users makes a lot of sense hosted on GitHub.

**Comment by dance2die** [comment]
@zaquestion 
>  it seems like a GitLab tutorial targeted at GitHub users makes a lot of sense hosted on GitHub.

One would not go into Whole Foods and promote Trader Joe's.
That said, would it make sense to go to Tune forum and write on how to switch to Singular?

**Comment by luong-komorebi** [comment]
I will close this issue, but feel free to leave any comments for further discussion. This will be hosted on Gitlab, or on any platform if you like (notice the MIT license). Right now I am not hosting this on Gitlab because of various reasons, but most of them are discussed (by others) already in this Hackernews topic (https://news.ycombinator.com/item?id=17294726) - look at the first comment, in the replies.
